In [58]:
import numpy as np

In [59]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [60]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [61]:
a.ndim

1

In [62]:
b.shape

(2, 3)

In [63]:
a.dtype

dtype('int32')

In [64]:
a.itemsize

4

In [65]:
a.nbytes

12

In [66]:
a.size

3

In [67]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
a[1, 5]

13

In [69]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
a[:, 2]

array([ 3, 10])

In [71]:
a[0, 1:-1:2]

array([2, 4, 6])

In [72]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [73]:
db = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [74]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [76]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [77]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [78]:
np.random.rand(4,2)

array([[0.90738186, 0.21235936],
       [0.88558694, 0.20903915],
       [0.84511479, 0.16910479],
       [0.85616345, 0.86497497]])

In [79]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1,  6, -3],
       [ 6,  0,  7],
       [ 3,  7,  0]])

In [80]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
